
val jaxws: Configuration by configurations.creating

plugins {
    id("sri-efactura-utils.java-library-conventions")
    idea
}

dependencies {
    implementation("com.sun.xml.ws:jaxws-rt:4.0.0")
    jaxws("com.sun.xml.ws:jaxws-tools:4.0.0")
}

/*
 * Add the Java code generated by wsimport to the main source set.
 * If using IntelliJ IDEA, mark this directory as generated source code.
 */
sourceSets {
    main {
        java {
            srcDir("$buildDir/generated/sources/wsimport/java")
        }
    }
}
idea {
    module {
        generatedSourceDirs.add(File("$buildDir/generated/sources/wsimport/java"))
    }
}


/*
 * Generate Java source for ec.gob.sri.ws services by executing
 * wsimport on the WSDL files located in resources/META-INF/wsdl/.
 *
 * If the WSDL definitions for the services change, replace the
 * WSDL resource files and the Java sources will be automatically updated.
 */
val wsdlDir = "${projectDir}/src/main/resources/META-INF/wsdl/"

fun wsdlFile(name: String) = File(wsdlDir, "${name}.wsdl")
val wsRecepcionOffline: Task = wsImport(
    wsdlFile("cel.sri.gob.ec.RecepcionComprobantesOffline"),
    "ec.gob.sri.ws.recepcion",
    "xsd.xjb")
val wsAutorizacionOffline: Task = wsImport(
    wsdlFile("cel.sri.gob.ec.AutorizacionComprobantesOffline"),
    "ec.gob.sri.ws.autorizacion",
    "xsd.xjb")
repositories {
    mavenCentral()
}

tasks.getByName("compileJava") {
    dependsOn(
        wsRecepcionOffline.path,
        wsAutorizacionOffline.path,
    )
}

fun wsImport(wsdl: File, packageName: String, vararg bindings: String): Task {
    val wsdlDir = wsdl.parent
    val taskName = "wsimport-${wsdl.nameWithoutExtension}"
    val bindStr = if (bindings.isNotEmpty()) { bindings.joinToString(",") } else null

    return task(taskName) {
        val sourcedestdir = file("$buildDir/generated/sources/wsimport/java")
        group = "code generation"
        inputs.file(wsdl)
        outputs.dir(sourcedestdir)
        doLast {
            sourcedestdir.mkdirs()
            bindStr?.apply {
                System.setProperty("javax.xml.accessExternalDTD", "file")
                System.setProperty("javax.xml.accessExternalSchema", "file")
            }
            ant.withGroovyBuilder {
                "taskdef"(
                    "name" to "wsimport",
                    "classname" to "com.sun.tools.ws.ant.WsImport",
                    "classpath" to jaxws.asPath
                )

                "wsimport"(
                    "keep" to true,
                    "Xnocompile" to true,
                    "sourcedestdir" to sourcedestdir,
                    "wsdl" to wsdl.absolutePath,
                    "wsdlLocation" to "http://localhost/wsdl/${wsdl.name}",
                    "package" to packageName,
                    "catalog" to File(wsdlDir, "catalog.cat"),
                ) {
                    bindStr?.apply {
                        "binding"("dir" to wsdlDir, "includes" to bindStr)
                    }
                    "xjcarg"("value" to "-XautoNameResolution")
                }
            }
        }
    }
}

